### PR TITLE
Add support to composite keys for updateAttributes

### PR DESCRIPTION
**Pull request by shenghu**
### Description
When using updateAttributes and the passed data contains primary columns (including partition keys and clustering keys), it failed w/ the error below. (See related issue for details). 

Uncaught AssertionError: expected ResponseError {
  name: 'ResponseError',
  info: 'Represents an error message from the server',
  message: 'PRIMARY KEY part str found in SET part',
  code: 8704,
  query: 'UPDATE "CASS_SORTABLE" SET "str"=?,"num"=?,"yearMonth"=? WHERE "patStr"=?'
} to not exist

#### Related issues

- connect to https://github.com/strongloop/loopback-connector-cassandra/issues/61

### Checklist

- [x] New tests added or existing tests modified to cover all changes
- [x] Code conforms with the [style guide](http://loopback.io/doc/en/contrib/style-guide.html)

### CODE REVIEW

**Comment by shenghu** [comment]
@jannyHou @dhmlau can you please review this change?

**Comment by shenghu** [comment]
@jannyHou hey, can you please review this?

**Comment by shenghu** [comment]
@slnode test please

**Comment by shenghu** [comment]
@bajtos @raymondfeng how does loopback-datasource-juggler support composite primary key?

**Comment by shenghu** [comment]
This pr now depends on https://github.com/strongloop/loopback-connector-cassandra/pull/66

**Comment by shenghu** [comment]
@slnode test please

**Comment by shenghu** [comment]
@slnode test again.

**Comment by shenghu** [comment]
@slnode please test

**Comment by bajtos** [comment]
> how does loopback-datasource-juggler support composite primary key?

I think composite keys are a feature that may work in theory but was never validated in practice, at least AFAIK. I would be surprised if composite keys were working out of the box as they are implemented now, especially when it comes to the REST API provided by LoopBack models.

**Comment by shenghu** [comment]
@bajtos composite keys are common in cassandra. Normally a partition key plus clustering keys. And clustering key can not be updated. This PR just avoid setting clustering key (and partition key) in update. Full support of composite keys may need change in juggler.

**Comment by dhmlau** [comment]
@bajtos @raymondfeng , any comments on how to go about this PR?

**Comment by raymondfeng** [comment]
The current juggler does not support composite key for `*ById` operations. I'm fine with the PR.

**Comment by dhmlau** [comment]
@slnode test please

**Comment by shenghu** [comment]
@raymondfeng do you have suggestion how to make juggler support composite primary keys? I think it is common requirement for relational db. And we probably need it on cassandra soon. Thanks for review.

**Comment by shenghu** [comment]
@dhmlau please let me whether this can proceed and be merged.

**Comment by raymondfeng** [comment]
@shenghu I approve it. Thanks!

**Comment by dhmlau** [comment]
Thanks @shenghu for your contribution. And sorry about the delay.  Your PR has landed.

**Pull request merged**
