### PR TITLE
suppport for passing multiple cluster nodes

### PR DESCRIPTION
**Pull request by anshulrvce**
### Description
support for passing array of cluster nodes as contact points in the config 

### Checklist

- [x] New tests added or existing tests modified to cover all changes
No new test case required
- [x] Code conforms with the [style
  guide](http://loopback.io/doc/en/contrib/style-guide.html)

### CODE REVIEW

**Comment by slnode** [comment]
Can one of the admins verify this patch?

**Comment by kjdelisle** [comment]
@slnode test please

**Comment by kjdelisle** [comment]
Additionally, this new feature should have documentation in the README describing what it enables and how to achieve it (by setting this option).

**Comment by anshulrvce** [comment]
@kjdelisle i have commited the change in README file and test cases

**Comment by anshulrvce** [comment]
@kjdelisle do i need to raise a new pull request for readme and test changes? As i have already committed the changes in this pull request

**Comment by anshulrvce** [comment]
Created another pull request for this change

**Pull request closed without merging**
